"""Run the Phase C acceptance criteria over adaptive ensembles and write the committed record.

Purpose: produce docs/phase_c_ensemble_record.md — each criterion's verdict, seeds used,
         per-readout difference, interval, margin, p, the fallback rate and any flag — stamped
         with a hash of the code and config it ran against (plan D7).
Spec:    docs/bowen_agent_model_spec_v2.md#M17.A.1, #M11.D.18, #M11.5, #M13.4
Tests:   tests/bowen/test_ensemble_record.py::test_m13_4_ensemble_record_is_current

    python3 tools/ensemble_record.py [--workers N] [--only ID ...]

The record is generated, never hand-edited. A default-suite test fails when the hash in the
record no longer matches the code and config, so a stale record cannot stand in for a run.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

RECORD = REPO / "docs" / "phase_c_ensemble_record.md"
HASHED_TOOLS = (Path(__file__).resolve(),)  # RULE_KEYS below is an input to the verdicts
RULE_KEYS = ("ensemble_block", "ensemble_cap", "ensemble_precision", "ensemble_margin", "ensemble_alpha",
             "fallback_flag_rate", "equivalence_margin")


def code_hash(*tools: Path) -> str:
    """Hash of everything a verdict depends on: engine, policy, scenario, ensemble, readouts and config.

    ``tools`` adds the generating tools whose own content is an input to a record, so changing one
    makes that record stale too: this file's ``RULE_KEYS`` (which constants become the ensemble rules,
    an input to every record), the mutant list of ``tools/mutation_record.py`` and the settings of
    ``tools/sweep_record.py``. Each record names its tools in its own ``HASHED_TOOLS``.
    """
    digest = hashlib.sha256()
    paths = sorted((REPO / "src" / "bowen").rglob("*.py")) + sorted((REPO / "config" / "bowen").rglob("*.md"))
    paths += sorted(Path(t).resolve() for t in tools)
    for path in paths:
        if path.name == "constants_changes.md":
            continue  # a log of changes, not an input
        digest.update(path.relative_to(REPO).as_posix().encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()


def run(workers: int, only: list[str] | None):
    from src.bowen.ensemble.criteria import CRITERIA, NOT_BUILT
    from src.bowen.ensemble.runner import run_criterion
    from src.bowen.io.load import load_constants

    constants = load_constants()
    rules = {k: constants[k] for k in RULE_KEYS}
    verdicts = []
    for cid, criterion in CRITERIA.items():
        if only and not any(cid.startswith(o) for o in only):
            continue
        started = time.time()
        verdict = run_criterion(criterion, rules, workers=workers)
        verdicts.append((verdict, time.time() - started))
        print(f"{cid}: {verdict.outcome} ({verdict.seeds} seeds, {time.time() - started:.0f} s)", flush=True)
    return verdicts, NOT_BUILT, rules


def scripted_cell(scripted: dict) -> str:
    """Each arm's scripted acts not made, of all it scripted: "—" for a criterion that scripts none."""
    if not scripted:
        return "—"
    return "; ".join(f"{arm} {c['not legal'] + c['not selecting']} of {sum(c.values())}" for arm, c in scripted.items())


def render(verdicts, not_built, rules, hash_: str) -> str:
    lines = [
        "# Phase C ensemble record",
        "",
        "Generated by `tools/ensemble_record.py`; do not edit. Each criterion's two arms ran on the same keyed",
        "seeds (`M3.D.4a`), stopped adaptively (`M17.A.1`, `M13.4`): `UNDETERMINED` at the seed cap does **not**",
        "pass. Every verdict carries its class (`M11.5`). **A premise passing confirms that the code renders the",
        "spec; it is not a finding about families.** The constants are the Phase C freeze of 2026-10-07.",
        "",
        f"code_hash: {hash_}",
        "",
        "Rules: " + ", ".join(f"`{k}` = {v}" for k, v in rules.items()) + ".",
        "",
        "| Criterion | Class | Verdict | Seeds | Readouts (difference treatment − baseline; ± half-width; p after Holm where tested) | Scripted acts not made (not legal + not selecting, of all scripted) | Fallback rate | Flags |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for v, _ in verdicts:
        parts = []
        for r in v.readouts:
            text = f"`{r['readout']}` {r['mean_difference']:+.3g} ± {r['half_width']:.2g}"
            if r.get("report_only"):
                text += " (reported only)"
            elif r["direction"] == 0:
                text += f", equivalence bound {r['equivalence_bound']:.3g}, {'within' if r['within_bound'] else 'outside'}"
            else:
                text += f", p {r['p']:.3g}, {'holds' if r.get('holds') else 'does not hold'}"
            parts.append(text)
        flags = list(v.flagged) + [f"move never occurred: {m}" for m in v.missing_moves]
        lines.append(f"| `{v.criterion}` | {v.cls} | **{v.outcome}** | {v.seeds} | {'; '.join(parts)} | "
                     f"{scripted_cell(v.scripted)} | {v.fallback_rate:.2f} | {'; '.join(flags) or '—'} |")
    lines += ["", "## Not built in Phase C", ""]
    lines += [f"- `{cid}` — {why}." for cid, why in not_built.items()]
    lines += ["", "## Fallback rate by person (`M11.D.18`)", ""]
    for v, _ in verdicts:
        worst = sorted(v.fallback_by_person.items(), key=lambda kv: -kv[1])[:3]
        lines.append(f"- `{v.criterion}`: " + ", ".join(f"{p} {r:.2f}" for p, r in worst))
    lines += ["", "## Machine-readable", "", "```json",
              json.dumps([{"criterion": v.criterion, "class": v.cls, "outcome": v.outcome, "seeds": v.seeds,
                           "readouts": v.readouts, "fallback_rate": v.fallback_rate, "flags": v.flagged,
                           "missing_moves": v.missing_moves, "scripted": v.scripted} for v, _ in verdicts], indent=1, default=float),
              "```", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workers", type=int, default=os.cpu_count() or 1)
    parser.add_argument("--only", nargs="*")
    args = parser.parse_args()
    verdicts, not_built, rules = run(args.workers, args.only)
    RECORD.write_text(render(verdicts, not_built, rules, code_hash(*HASHED_TOOLS)), encoding="utf-8")
    print(f"wrote {RECORD.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
