"""Measure the functional levels M11.C.16's members occupy, unmodified and under the availability inversion.

Purpose: give the share of member-weeks at which `availability-level-inverted` equals the deletion, so that report
         §11's qualification of that mutant comes from a generated, hash-stamped record and not a scratch probe.
Spec:    docs/bowen_agent_model_spec_v2.md#M11.1a, #M11.C.16
Tests:   tests/bowen/test_ensemble_record.py::test_m111a_level_occupancy_record_is_current

    python3 tools/level_occupancy.py

Each variant runs in a temporary copy of the repository (the mutant from ``tools/mutation_record.py`` applied there,
never to the working tree), over C.16's own arms, settings and declared spell. Every member's functional level is
sampled at the start of every week. The thresholds are where the inversion, (0.6 × SCALE_MAX − level) /
(layer × capacity_level_per_layer), clamps: at or below 0.2 × SCALE_MAX it equals the deletion on both layers, at or
below 0.4 × SCALE_MAX on layer 1, and above 0.6 × SCALE_MAX it is 0 on every layer. SEEDS is [I], declared here: an
occupancy share is a mean over thousands of member-weeks and does not need the criterion's seed count.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from tools.mutation_record import MUTANTS, apply  # noqa: E402

RECORD = REPO / "docs" / "phase_c_level_occupancy.md"
HASHED_TOOLS = (Path(__file__).resolve(), REPO / "tools" / "mutation_record.py", REPO / "tools" / "ensemble_record.py")
SEEDS = 20
VARIANTS = (None, "availability-level-inverted")
THRESHOLDS = (("at_or_below_0.2", 0.2, "le"), ("at_or_below_0.4", 0.4, "le"), ("above_0.6", 0.6, "gt"))


def child() -> None:
    """Run in the (possibly mutated) copy: print one JSON line per arm."""
    import src.bowen.ensemble.criteria as criteria
    from src.bowen.engine.objects import SCALE_MAX

    settings = criteria.SETTINGS["M11.C.16"]
    original = criteria.run_tick
    for arm, by in (("baseline", settings["level_baseline"]), ("treatment", settings["level_treatment"])):
        seen: list[float] = []

        def sampled(state, *args, **kwargs):
            seen.extend(p.functional_level for p in state.people.values() if p.role.value == "member")
            return original(state, *args, **kwargs)

        criteria.run_tick = sampled
        try:
            for seed in range(SEEDS):
                criteria.scenario("phase_c", seed, settings["weeks"], spells=criteria.spell("phase_c", settings["weeks"]),
                                  setup=criteria.lowered(by))
        finally:
            criteria.run_tick = original
        shares = {name: sum(1 for v in seen if (v <= f * SCALE_MAX if op == "le" else v > f * SCALE_MAX)) / len(seen)
                  for name, f, op in THRESHOLDS}
        print(json.dumps({"arm": arm, "member_weeks": len(seen), "shares": shares}), flush=True)


def run_variant(mutant_id: str | None) -> list[dict]:
    with tempfile.TemporaryDirectory(prefix="bowen-occupancy-") as tmp:
        root = Path(tmp)
        for part in ("src", "config", "tools"):
            shutil.copytree(REPO / part, root / part, ignore=shutil.ignore_patterns("__pycache__"))
        if mutant_id:
            apply(root, next(m for m in MUTANTS if m.id == mutant_id))
        out = subprocess.run([sys.executable, str(root / "tools" / "level_occupancy.py"), "--child"], cwd=root,
                             capture_output=True, text=True, timeout=3600)
        if out.returncode != 0:
            raise SystemExit(f"variant {mutant_id} failed:\n{out.stderr[-2000:]}")
        return [json.loads(line) for line in out.stdout.splitlines() if line.startswith("{")]


def render(rows: list[dict], hash_: str) -> str:
    lines = [
        "# M11.C.16 level occupancy",
        "",
        "Generated by `tools/level_occupancy.py`; do not edit. The share of member-weeks in each of C.16's arms at",
        f"which members' functional level lies in each range, over {SEEDS} seeds, unmodified and under",
        "`availability-level-inverted`. At or below 0.2 of the scale that mutant equals the deletion on both layers;",
        "at or below 0.4, on layer 1; above 0.6 it makes layers 1 and 2 unavailable.",
        "",
        f"code_hash: {hash_}",
        "",
        "| Variant | Arm | Member-weeks | ≤ 0.2 | ≤ 0.4 | > 0.6 |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        s = r["shares"]
        lines.append(f"| {r['variant']} | {r['arm']} | {r['member_weeks']} | {s['at_or_below_0.2']:.1%} | "
                     f"{s['at_or_below_0.4']:.1%} | {s['above_0.6']:.1%} |")
    lines += ["", "## Machine-readable", "", "```json", json.dumps(rows, indent=1), "```", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--child", action="store_true")
    args = parser.parse_args()
    if args.child:
        child()
        return 0
    from tools.ensemble_record import code_hash

    rows = []
    for variant in VARIANTS:
        for r in run_variant(variant):
            rows.append({"variant": variant or "unmodified", **r})
            print(f"{variant or 'unmodified'} {r['arm']}: {r['shares']}", flush=True)
    RECORD.write_text(render(rows, code_hash(*HASHED_TOOLS)), encoding="utf-8")
    print(f"wrote {RECORD.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
