"""Prove each acceptance test can fail: apply its mutation, run only that test, restore.

Purpose: produce the mutation record a phase's completion report needs — for
         every gate test, a baseline pass and a red run under its mutation.
Spec:    docs/bowen_agent_model_spec_v2.md#M11 (each criterion "proved failing by
         mutation before it counts as coverage"); docs/implementation_plan_phase_b.md §2, step 14
Tests:   run it; it exits non-zero if any gate is not proved

    python3 tools/mutation_gate.py tools/mutation_gate_phase_b.json docs/phase_b_mutation_record.md

Every file a mutation touches is restored in a ``finally`` block, whether the
edit, the test run or anything else fails. (At Phase B step 11 a shell loop's
backups failed silently while its edits succeeded and left mutations in the
tree; this harness exists so that cannot recur.) A mutation whose search text
is not found exactly once is an error, never a silent no-op.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TIMEOUT_SECONDS = 600


def run_node(node: str) -> tuple[bool, str]:
    result = subprocess.run(
        [sys.executable, "-m", "pytest", node, "-q", "-p", "no:cacheprovider"],
        cwd=REPO, capture_output=True, text=True, timeout=TIMEOUT_SECONDS,
    )
    tail = (result.stdout.strip().splitlines() or ["(no output)"])[-1]
    return result.returncode == 0, tail


def prove(gate: dict) -> dict:
    baseline_ok, baseline_tail = run_node(gate["test"])
    originals: dict[Path, str] = {}
    try:
        for relative, old, new in gate["edits"]:
            path = REPO / relative
            text = originals.setdefault(path, path.read_text(encoding="utf-8"))
            current = path.read_text(encoding="utf-8")
            count = current.count(old)
            if count != 1:
                raise ValueError(f"{gate['gate']}: search text found {count} times in {relative}")
            path.write_text(current.replace(old, new), encoding="utf-8")
        mutant_ok, mutant_tail = run_node(gate["test"])
    finally:
        for path, text in originals.items():
            path.write_text(text, encoding="utf-8")
    return {
        **gate,
        "baseline": baseline_tail,
        "mutant": mutant_tail,
        "proved": baseline_ok and not mutant_ok,
    }


def render(results: list[dict], spec_name: str) -> str:
    lines = [
        "# Phase B — mutation record",
        "",
        f"Generated by `tools/mutation_gate.py {spec_name}`. Each gate test passes unmutated",
        "(baseline), then fails under its mutation, run alone. Files are restored after every mutation.",
        "",
        "| Gate | Test | Mutation | Baseline | Under mutation | Proved |",
        "|---|---|---|---|---|---|",
    ]
    for r in results:
        lines.append(
            f"| {r['gate']} | `{r['test'].split('::')[-1]}` | {r['mutation']} | {r['baseline']} | "
            f"{r['mutant']} | {'yes' if r['proved'] else '**NO**'} |"
        )
    proved = sum(r["proved"] for r in results)
    lines += ["", f"{proved} of {len(results)} gates proved.", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    spec_path, out_path = Path(argv[1]), Path(argv[2])
    gates = json.loads(spec_path.read_text(encoding="utf-8"))
    results = [prove(g) for g in gates]
    out_path.write_text(render(results, spec_path.name), encoding="utf-8")
    for r in results:
        print(f"{r['gate']:<4} {'proved' if r['proved'] else 'NOT PROVED':<11} {r['mutant']}")
    unchanged = subprocess.run(["git", "status", "--porcelain", "--", "src", "tests", "config", "docs/bowen_agent_model_spec_v2.md"],
                               cwd=REPO, capture_output=True, text=True, timeout=60).stdout
    print("working tree after run:", "clean" if not unchanged.strip() else unchanged)
    return 0 if all(r["proved"] for r in results) else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
