"""Run the composite Phase C criteria at low and high settings of the learner's constants (plan D9).

Purpose: report, for each composite criterion, its verdict and each readout's direction at a low and a
         high declared setting of the learning rate α, the credit horizon H and the policy temperature,
         beside the central setting in docs/phase_c_ensemble_record.md, and flag a direction that reverses.
Spec:    docs/bowen_agent_model_spec_v2.md#M11.5, #M17.E.1; docs/implementation_plan_phase_c.md#D9
Tests:   tests/bowen/test_ensemble_record.py::test_d9_sweep_record_is_current

    python3 tools/sweep_record.py [--workers N]

Each setting is a one-row change to ``config/bowen/constants.md`` in a temporary copy of the repository
(the working tree's frozen constants are never touched). The gate is the central setting; these
settings are reported, not gated. The settings — half and double the central value — are [I], declared
here before the sweep ran. Plan D9 also asks for each criterion's "dominant constant"; plan §3 names
none, so it is not swept, and the record says so.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from tools.mutant_runner import Mutant  # noqa: E402
from tools.record_cache import Cache, engine_hash, result_key, run_cached  # noqa: E402
from tools.mutation_record import ENSEMBLE_RECORD  # noqa: E402

RECORD = REPO / "docs" / "phase_c_sweep_record.md"
# Results are cached by tools/mutant_runner.py under the engine hash and each setting's edit; this file only
# chooses the settings and renders, so editing it reruns nothing unless a setting changes.
CONSTANTS = "config/bowen/constants.md"
SETTINGS = (  # (constant, central as written in constants.md, low, high)
    ("learning_rate", "0.2", "0.1", "0.4"),
    ("credit_horizon", "3", "2", "6"),
    ("policy_temperature", "1.0", "0.5", "2.0"),
)


def row_mutant(name: str, central: str, value: str) -> Mutant:
    text = (REPO / CONSTANTS).read_text(encoding="utf-8")
    line = next(l for l in text.splitlines() if l.startswith(f"| `{name}` | "))
    old = f"| `{name}` | {central} |"
    if not line.startswith(old):
        raise SystemExit(f"{name}: central value in {CONSTANTS} is not {central}: {line}")
    return Mutant(f"{name}={value}", "sweep", ("*",), CONSTANTS, old + " ", f"| `{name}` | {value} | ",
                  f"{name} {value} (central {central})")


def central() -> dict[str, dict]:
    text = ENSEMBLE_RECORD.read_text(encoding="utf-8")
    data = json.loads(re.search(r"```json\n(.*?)\n```", text, re.S).group(1))
    return {row["criterion"]: row for row in data}


def render(rows, centrals, engine: str) -> str:
    lines = [
        "# Phase C sweep record (plan D9)",
        "",
        "Generated by `tools/sweep_record.py`; do not edit. Each composite criterion (`M11.5`) at half and double",
        "the central value of the learner's α (`learning_rate`), horizon (`credit_horizon`) and the policy",
        "temperature (`policy_temperature`), one constant at a time. **Only the central setting gates**",
        "(`docs/phase_c_ensemble_record.md`); these are reported. A readout whose mean difference has the",
        "opposite sign to the declared direction is marked **opposite sign**, whatever its interval; this is not",
        "the mutation record's **reversed**, which needs every gating interval wholly on the opposite side. A",
        "readout reported beside the verdict and never tested is marked *(report only)*. Plan D9's fourth",
        "constant, each criterion's dominant constant, is not swept: plan §3 names none.",
        "",
        f"engine_hash: {engine}",
        "",
        "Results are cached by `tools/mutant_runner.py` (`docs/records_cache/sweep.json`); this file is rendered",
        "from that cache.",
        "",
        "| Criterion | Central verdict | Setting | Verdict | Seeds | Readouts (mean difference; direction) |",
        "|---|---|---|---|---|---|",
    ]
    for setting, r in rows:
        parts = []
        for x in r.get("readouts", ()):  # a RAISED or BROKEN row carries none
            mark = ""
            if x["direction"] and x["mean_difference"] * x["direction"] < 0:
                mark = " **opposite sign**"
            if x.get("report_only"):
                mark += " *(report only)*"
            parts.append(f"`{x['readout']}` {x['mean_difference']:+.3g}{mark}")
        if r.get("error"):
            parts.append(f"*{r['error']}*")
        lines.append(f"| `{r['criterion']}` | {centrals[r['criterion']]['outcome']} | {setting} | {r['outcome']} | "
                     f"{r['seeds']} | {'; '.join(parts)} |")
    lines += ["", "## Machine-readable", "", "```json",
              json.dumps([{"setting": s, **r} for s, r in rows], indent=1, default=float), "```", ""]
    return "\n".join(lines)


def build(cache: Cache, workers: int | None = None) -> str:
    """The record, from the cache. With ``workers``, missing results are run first; without, a missing result raises
    KeyError, so a test can check the committed record without running anything."""
    from src.bowen.ensemble.criteria import CRITERIA

    centrals, engine = central(), engine_hash()
    ids = [cid for cid, c in CRITERIA.items() if c.cls == "composite"]
    rows = []
    for name, middle, low, high in SETTINGS:
        for value in (low, high):
            mutant = row_mutant(name, middle, value)
            if workers is not None:
                results = run_cached(cache, mutant, ids, workers)
            else:
                results = [cache.get(result_key(engine, mutant.definition(), cid)) for cid in ids]
                if None in results:
                    raise KeyError(f"{mutant.id}: no cached result for the current engine and setting")
            rows += [(mutant.what.split(" (")[0], result) for result in results]
    return render(rows, centrals, engine)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workers", type=int, default=os.cpu_count() or 1)
    args = parser.parse_args()
    cache = Cache("sweep")
    text = build(cache, args.workers)
    cache.save()
    RECORD.write_text(text, encoding="utf-8")
    print(f"wrote {RECORD.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
